mapbox/mapbox-gl-directions

dist/mapbox-gl-directions.js
example/index.html
example/index.js
index.js
package.json
src/controls/geocoder.js
src/controls/inputs.js
src/controls/instructions.js
src/directions.js

* Removes dependency on mapboxgl.Directions. Vendors that library. This is so that I can fix bugs in it without a new release, and so that the two modules can share modules and avoid build systems messups.
* Removes require-time dependency on mapboxgl. This is not a guarantee with webpack and other systems, and the previous check was broken ( #84 ) in both modules ( #53 )
* That's it, trying to make this the smallest possible change required to make mapbox-gl-directions friendly with webpack async loading

Defer mapboxgl dependency to runtime

---

src/mapbox-gl-directions.css

Fixes a case where icons were not aligning due to different global `line-height` properties. This updates the icons within the depart/arrival space to fit the width of the label and position themselves in the exact center, no matter what.
Issue appeared in #98

background image center

---

CHANGELOG.md
package.json
src/directions.js
src/reducers/index.js

Adds an `if` statement to hide the instructions panel based on options: #101 
Introduces node deep-assign to start resolving #103 
cc @rolandoldengarm @tmcw

deep assign objects, hide instructions

---

API.md
src/directions.js
src/index.js

Constructor options were in `index.js`, but they should have been in `direction.js` with the real constructor. Fixes discussion in #107 
cc @tmcw

bring back the constructor options

---

src/directions.js

Right now, if you create an instance, then remove it, then add a new instance, it breaks since they share the same store. The old subscription still runs but `this.map` is undefined and so `this.map.styles` on `subscribedActions` breaks.
This fix is kind-of a hack. The question is: Should each instance have its own store? If so, then we should change any reference to `store` to `this.store` and create a new store in the constructor. 
I really do think that creating a store-per-instance might be the right approach, but even then we'd want to unsubscribe ourselves from our own store to remove a reference and possible memory leak so this PR would still be beneficial. In the short term this will fix the bug and not change anything about the "shared store" that is used right now.

Unsubscribe from store on remove

---

CONTRIBUTING.md
circle.yml
package.json

This PR adds a deployment script which publishes `mapbox-gl-directions` to s3 via CircleCI whenever a release tag is pushed to GitHub. This frees us from having to do deployment manually within the GL JS repository.
- should we also deploy to our `cn-north-1` bucket?

Add deployment script which publishes to s3

---

README.md

Described this plugin with language similar to MapboxDirections.swift’s readme description. Linked to GL-compatible directions libraries for other platforms, since “Mapbox GL Directions” could be misinterpreted to mean directions for any Mapbox GL library.
/cc @captainbarbosa @mollymerp @friedbunny

Mention other GL-compatible directions libraries

---

package.json

Move these `devDependencies` under `dependencies` was needed in order to `require()` this project from another browserify project.

Babelify dependencies

---

src/controls/inputs.js
src/directions.js
src/reducers/index.js
src/templates/inputs.html

This adds the ability to show/hide the profile switcher. Useful alongside https://github.com/mapbox/mapbox-gl-directions/pull/138.

Toggle or disable profile switcher.

---

package.json
test/test.inputs.js

Fixes #150. 
This also gets tests passing — looks like profile values were prefixed with `mapbox/` in https://github.com/mapbox/mapbox-gl-directions/commit/485e01312702262d669de49811c4bba590b63e9e but tests were not updated.

Bump mapbox-gl version

---

src/controls/geocoder.js
src/utils.js
test/index.js
test/test.utils.js

Follow-up to https://github.com/mapbox/mapbox-gl-directions/pull/154, but preserves original decimal length if it's less than 5.
Also adds a `utils` test file to test a new method, but it needs more 🍔! Our test suite is 😱 
Fixes https://github.com/mapbox/mapbox-gl-directions/issues/156.

Round input floats to original precision if < 5

---

test/index.js

fail with a helpful message if no access token is set

---

src/directions.js
test/test.directions.js

when custom styles are being used, this plugin was adding _both_ the default and the custom layers to the map which was uncaught by mapbox-gl-js until https://github.com/mapbox/mapbox-gl-js/pull/6147

don't add duplicate layers when custom styles are provided

---

src/actions/index.js

this happens when a user sets the origin with a click on the map.

do not make directions api request if there is no set destination

---

API.md

Actually it was way confusing. We were looking for `clear` option, but we end up spending an hour for hunting the same, and later we  realized that `clear` is there, but It was not clear because of `mis-alignment`.

`clear` event option wasn't aligned with the doc

---

src/controls/inputs.js
src/directions.js
src/reducers/index.js

This PR makes padding surrounding a route configurable on a MapboxDirections object. Padding is currently set to 80. This allows for users to pass in a specific number of pixels or a [PaddingOptions](https://docs.mapbox.com/mapbox-gl-js/api/#paddingoptions) object. Especially useful for making sure no part of the route is hidden by the location of the directions control on top of the map.

Make route padding configurable

---

src/actions/index.js

Fixes https://github.com/mapbox/mapbox-gl-directions/issues/245
With the current behavior, when reversing origin and destination, dropdown suggestions are displayed again which leads to a confusing UI. 
Proposed behavior simply reverses the points (and step-by-step directions) and hides suggestions when reversing.

Remove dropdown suggestions when reversing origin and destination

---

src/controls/geocoder.js

Since mapbox-gl-directions 4.0.0, specifying a custom API for the geocoder control has worked, but also inserts the `api` option as a query parameter, leading to requests like `https://api2.mapbox.com/geocoding/v5/mapbox.places/test.json?api=https://api2.mapbox.com/geocoding/v5/mapbox.places/&access_token=`
While this doesn't cause an error, it isn't the desired behavior. This PR adds `api` to the list of geocoder options excluded from the URL parameters.

Exclude options.api from query params

---

src/actions/index.js

Currently routes that return 'No route found' cause the following error: 
```
TypeError: Cannot read property '0' of undefined
at XMLHttpRequest.request.onload (/mapbox-gl-js/plugins/mapbox-gl-directions/v3.1.1/mapbox-gl-directions.js:5819:44)
```
This change catches these responses and displays the appropriate message to the user (see screenshot above).

Catch 'No Route found' response

---

src/actions/index.js

Currently the removeRoutes() function doesn't abort any ongoing requests which may cause the symbols to be redrawn on the map after calling removeRoutes()
This bug occurs frequentally to users with slow internet as the request may take longer time to be loaded while the removeRoutes() was already called

fix: request is loaded after removeRoutes() is called

---

src/controls/instructions.js

Hi
I have a question about this.
They seem to be given the wrong values for the duration and distance variables.
In [src/controls/instructions.js on lines 55 and 56](https://github.com/YuChunTsao/mapbox-gl-directions/blob/master/src/controls/instructions.js#L55-L56)
```js
duration: utils.format[unit](direction.distance),
distance: utils.format.duration(direction.duration)
```
The duration and distance values should be exchanged
like this
```js
duration: utils.format.duration(direction.duration),
distance: utils.format[unit](direction.distance)
```

Fix the duration and distance values

---

.circleci/config.yml

Publishing the latest release to CDN didn't work because of the missing `mbx-ci aws setup` step.

Fix AWS setup for publishing

---

package-lock.json
package.json
src/reducers/index.js

Replaced `lodash.merge` with `merge-options` (based on [two options recommended in deprecation notice](https://www.npmjs.com/package/deep-assign) of `deep-assign` library). Noticed, that `lodash.merge` added ~50KB of code, which significantly increase size of bundle without proper reason for that. Now situation with `merge-options` much better:
- `lodash.merge` 50.1KB
- `merge-options` 4.1 KB
- `deep-assign` 1.3 KB

Replaced lodash.merge with merge-options

---

CHANGELOG.md
package-lock.json
package.json

- [feature] Display waypoints-related instructions [#310](https://github.com/mapbox/mapbox-gl-directions/pull/310)
- [chore] Update mapbox-gl peer dependency to support version 3 [#310](https://github.com/mapbox/mapbox-gl-directions/pull/310)
- [chore] Fixed launching of tests [#310](https://github.com/mapbox/mapbox-gl-directions/pull/310)

Release 4.2.0

---

CHANGELOG.md
package-lock.json
package.json

- [feature] Added option `instructions.showWaypointInstructions` to control displaying of waypoint instructions [#313](https://github.com/mapbox/mapbox-gl-directions/pull/313)

Release 4.3.0
